services:
  backend:
    image: keymanagement-backend:latest
    build: ./Backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: keymanagement-frontend:latest
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
