@baseUrl = http://localhost:5000/api/auth
@contentType = application/json

### Login and save token
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "username": "testuser",
    "password": "testpass123"
}

###
@authToken = {{login.response.body.access_token}}

### Use saved token
POST {{baseUrl}}/change-password
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "old_password": "testpass123",
    "new_password": "newpass123"
} 